"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


ENVIRONMENT = os.environ.get('DJANGO_ENVIRONMENT', 'development')
IS_PRODUCTION = ENVIRONMENT == 'production'


def require_production_settings(*names):
    if not IS_PRODUCTION:
        return
    missing = [name for name in names if not os.environ.get(name)]
    if missing:
        raise ImproperlyConfigured(
            f'Missing required production environment variables: {", ".join(missing)}',
        )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
require_production_settings(
    'DJANGO_SECRET_KEY',
    'DJANGO_ALLOWED_HOSTS',
    'DATABASE_URL',
    'CORS_ALLOWED_ORIGINS',
    'CSRF_TRUSTED_ORIGINS',
)

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-development-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', not IS_PRODUCTION)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'core',
    'documents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if ENVIRONMENT in {'build', 'production'}:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=int(os.environ.get('DATABASE_CONN_MAX_AGE', 60)),
            conn_health_checks=True,
            ssl_require=env_bool('DATABASE_SSL_REQUIRE', IS_PRODUCTION),
        ),
    }
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = env_bool(
        'DATABASE_DISABLE_SERVER_SIDE_CURSORS',
        IS_PRODUCTION,
    )
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'academic_research_assistant'),
            'USER': os.environ.get('POSTGRES_USER', 'academic_research_assistant'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'academic_research_assistant_dev_password'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get('DJANGO_STATIC_URL', '/static/')
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT') or BASE_DIR / 'staticfiles')
MEDIA_URL = os.environ.get('DJANGO_MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT') or BASE_DIR / 'media')

DOCUMENT_STORAGE_BACKEND = os.environ.get('DOCUMENT_STORAGE_BACKEND', 'filesystem')
if IS_PRODUCTION and DOCUMENT_STORAGE_BACKEND != 's3':
    raise ImproperlyConfigured('Production requires DOCUMENT_STORAGE_BACKEND=s3.')

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
if DOCUMENT_STORAGE_BACKEND == 's3':
    require_production_settings(
        'DOCUMENT_STORAGE_BUCKET',
        'DOCUMENT_STORAGE_ENDPOINT_URL',
        'DOCUMENT_STORAGE_ACCESS_KEY',
        'DOCUMENT_STORAGE_SECRET_KEY',
    )
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': os.environ.get('DOCUMENT_STORAGE_BUCKET'),
            'endpoint_url': os.environ.get('DOCUMENT_STORAGE_ENDPOINT_URL'),
            'access_key': os.environ.get('DOCUMENT_STORAGE_ACCESS_KEY'),
            'secret_key': os.environ.get('DOCUMENT_STORAGE_SECRET_KEY'),
            'region_name': os.environ.get('DOCUMENT_STORAGE_REGION', 'us-east-1'),
            'signature_version': 's3v4',
            'addressing_style': os.environ.get('DOCUMENT_STORAGE_ADDRESSING_STYLE', 'path'),
            'default_acl': None,
            'querystring_auth': True,
            'file_overwrite': False,
        },
    }
else:
    STORAGES['default'] = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {'location': MEDIA_ROOT, 'base_url': MEDIA_URL},
    }

DOCUMENT_UPLOAD_MAX_BYTES = int(os.environ.get('DOCUMENT_UPLOAD_MAX_BYTES', 10 * 1024 * 1024))
DOCUMENT_CHUNK_SIZE = int(os.environ.get('DOCUMENT_CHUNK_SIZE', 1000))
DOCUMENT_CHUNK_OVERLAP = int(os.environ.get('DOCUMENT_CHUNK_OVERLAP', 200))
EMBEDDING_PROVIDER = os.environ.get('EMBEDDING_PROVIDER', 'sentence_transformers')
EMBEDDING_MODEL_NAME = os.environ.get(
    'EMBEDDING_MODEL_NAME',
    'sentence-transformers/all-MiniLM-L6-v2',
)
EMBEDDING_DIMENSIONS = int(os.environ.get('EMBEDDING_DIMENSIONS', 384))
EMBEDDING_BATCH_SIZE = int(os.environ.get('EMBEDDING_BATCH_SIZE', 32))
EMBEDDING_ONNX_MODEL_PATH = os.environ.get('EMBEDDING_ONNX_MODEL_PATH', '')
EMBEDDING_ONNX_TOKENIZER_PATH = os.environ.get('EMBEDDING_ONNX_TOKENIZER_PATH', '')
EMBEDDING_ONNX_BATCH_SIZE = int(os.environ.get('EMBEDDING_ONNX_BATCH_SIZE', 8))
EMBEDDING_ONNX_MAX_SEQUENCE_LENGTH = int(
    os.environ.get('EMBEDDING_ONNX_MAX_SEQUENCE_LENGTH', 256),
)
EMBEDDING_ONNX_INTRA_OP_THREADS = int(os.environ.get('EMBEDDING_ONNX_INTRA_OP_THREADS', 1))
EMBEDDING_ONNX_INTER_OP_THREADS = int(os.environ.get('EMBEDDING_ONNX_INTER_OP_THREADS', 1))
LLM_PROVIDER = os.environ.get('LLM_PROVIDER', 'groq')
LLM_MODEL = os.environ.get('LLM_MODEL', 'openai/gpt-oss-20b')
LLM_API_KEY = os.environ.get('GROQ_API_KEY', '')
LLM_API_BASE_URL = os.environ.get('LLM_API_BASE_URL', 'https://api.groq.com/openai/v1')
LLM_TIMEOUT_SECONDS = float(os.environ.get('LLM_TIMEOUT_SECONDS', 30))
LLM_MAX_CONTEXT_CHARS = int(os.environ.get('LLM_MAX_CONTEXT_CHARS', 12000))
LLM_MAX_SOURCE_CHARS = int(os.environ.get('LLM_MAX_SOURCE_CHARS', 2500))
LLM_MAX_OUTPUT_TOKENS = int(os.environ.get('LLM_MAX_OUTPUT_TOKENS', 700))
LLM_MODEL_CONTEXT_WINDOW = int(os.environ.get('LLM_MODEL_CONTEXT_WINDOW', 131072))
LLM_PROMPT_OVERHEAD_TOKENS = int(os.environ.get('LLM_PROMPT_OVERHEAD_TOKENS', 1200))
LLM_QUESTION_MAX_CHARS = int(os.environ.get('LLM_QUESTION_MAX_CHARS', 1000))
LLM_ASK_TOP_K_MAX = int(os.environ.get('LLM_ASK_TOP_K_MAX', 10))
LLM_TEMPERATURE = float(os.environ.get('LLM_TEMPERATURE', 0.1))
LLM_ASK_THROTTLE_RATE = os.environ.get('LLM_ASK_THROTTLE_RATE', '10/minute')
LLM_GROQ_SUPPORTED_MODELS = [
    model.strip()
    for model in os.environ.get(
        'LLM_GROQ_SUPPORTED_MODELS',
        'openai/gpt-oss-20b,openai/gpt-oss-120b,llama-3.1-8b-instant,llama-3.3-70b-versatile',
    ).split(',')
    if model.strip()
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)

SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https')
    if env_bool('DJANGO_SECURE_PROXY_SSL_HEADER_ENABLED', IS_PRODUCTION)
    else None
)
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', IS_PRODUCTION)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', IS_PRODUCTION)
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', 31536000 if IS_PRODUCTION else 0))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'collection_ask': LLM_ASK_THROTTLE_RATE,
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}
