# Generated by Django 5.2.17 on 2026-09-15 22:39

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_page_count_document_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_status',
            field=models.CharField(choices=[('not_embedded', 'Not embedded'), ('embedding', 'Embedding'), ('embedded', 'Embedded'), ('failed', 'Failed')], default='not_embedded', max_length=20),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(condition=models.Q(('embedding__isnull', False)), ef_construction=64, fields=['embedding'], m=16, name='document_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
